---@class Module : ModuleAPI, ClassDefinition

---@class Core
---@field threads? Threads
---@field modules table<string, any>
---@field load fun(self: Core): void
---@field init fun(self: Core): void

---@class CharacterData
---@field uuid string
---@field id number
---@field account string
---@field date string
---@field gender 'male' | 'female'
---@field job string
---@field roles table
---@field bank number
---@field money number
---@field slots number
---@field experience number
---@field timeplayed number
---@field energy number
---@field health number
---@field position table
---@field created_at number
---@field updated_at number